# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Di9uk1VdQ6RCD6DqezmAyoa6is5NRE4e
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

url = "https://raw.githubusercontent.com/bmounikareddy98/Machine-learning-assignments/main/Job_recommendation.csv?token=GHSAT0AAAAAABTE75RGZET4KXX4POU2IJ3WYSIZTQA"
df = pd.read_csv(url)
df=df.dropna()


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Role"] = le.fit_transform(df["Role"])


dom = pd.get_dummies(df["Domain"], drop_first=True)
df = pd.concat([df.drop("Domain", axis=1), dom], axis=1)
df.head()


from sklearn.model_selection import train_test_split
X = df[["Age", "Career Gap", "Experience", "EstimatedSalary", "Human Resources", "Information Technology", "Interior Design", "Legal", "Media", "Medicine", "Project Management","Pyschology"]]
y = df["Role"]

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X= sc.fit_transform(X) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=103)

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

y_pred = classifier.predict(X_test)
#le.inverse_transform(y_pred)


l =[[19,8,6,10000,0,0,0,1,0,0,0,0]]

def output(a):
    l[0] = a
    ans = classifier.predict(np.array(l))
    return le.inverse_transform(ans)





